### PR TITLE
Change to support newer ROS2 versions

### PR DESCRIPTION
**Pull request by bascetta74**
In order to make the CMakeList compatible with newer ROS2 versions, like humble, rosidl_target_interfaces() must be changed in favor of rosidl_get_typesupport_target().

### CODE REVIEW

**Comment by andrea-testa** [comment]
Hi, thank you for this request. I will check all the commits and eventually merge them in the next few days. Sorry for the delay, it's a hard-working period.  Can you re-open it again? Or did you delete the branch for other issues?

**Comment by bascetta74** [comment]
Dear Andrea,

I forked again as I see you added other branches, I will complete the work and create again the pull request.

Regards,
Luca Bascetta


Luca Bascetta, PhD.
Associate Professor
Chair of the Agricultural Engineering Study Programme

Politecnico di Milano
***@***.***
bascetta.deib.polimi.it<http://bascetta.deib.polimi.it>

[cid:1738f9a4-76ef-4a5d-9fbd-0589b87d4b39]


________________________________
Da: Andrea Testa ***@***.***>
Inviato: mercoledì 12 luglio 2023 11:27
A: OPT4SMART/ros2-vicon-receiver ***@***.***>
Cc: Luca Bascetta ***@***.***>; State change ***@***.***>
Oggetto: Re: [OPT4SMART/ros2-vicon-receiver] Change to support newer ROS2 versions (PR #7)


Hi, thank you for this request. I will check all the commits and eventually merge them in the next few days. Sorry for the delay, it's a hard-working period. Can you re-open it again? Or did you delete the branch for other issues?

**Comment by andreacamisa** [comment]
Please only include in the new PR only the necessary changes to support newer ROS2 versions. I assume it's just `CMakeLists.txt`. If you wish, you can open a separate PR for updating DataStreamSDK to 12.1.

**Comment by bascetta74** [comment]
Unfortunately that commit is in between other commits, I can avoid pulling the commit I did after, but I do not know how to avoid pulling the commit I do before (that include adding the new SDK).

I will avoid doing the PR.


Luca Bascetta, PhD.
Associate Professor
Chair of the Agricultural Engineering Study Programme

Politecnico di Milano
***@***.***
bascetta.deib.polimi.it<http://bascetta.deib.polimi.it>

[cid:29bd4788-1945-4ed0-8a87-6d081757d6eb]


________________________________
Da: Andrea Camisa ***@***.***>
Inviato: lunedì 17 luglio 2023 13:13
A: OPT4SMART/ros2-vicon-receiver ***@***.***>
Cc: Luca Bascetta ***@***.***>; State change ***@***.***>
Oggetto: Re: [OPT4SMART/ros2-vicon-receiver] Change to support newer ROS2 versions (PR #7)


Please only include in the new PR only the necessary changes to support newer ROS2 versions. I assume it's just CMakeLists.txt. If you wish, you can open a separate PR for updating DataStreamSDK to 12.1.

**Pull request closed without merging**
